services:

  db:
    image: mariadb:11
    container_name: sql_injection_db
    restart: on-failure:5
    environment:
      MARIADB_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MARIADB_DATABASE: ${MYSQL_DATABASE}
      MARIADB_USER: ${MYSQL_USER}
      MARIADB_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
      - ./mariadb:/docker-entrypoint-initdb.d:ro
    networks:
      - sql_injection_net

  php:
    build:
      context: .
      dockerfile: php/Dockerfile
    container_name: sql_injection_php
    restart: on-failure
    environment:
      db_host: db
      db_user: ${MYSQL_USER}
      db_pass: ${MYSQL_PASSWORD}
      db_name: ${MYSQL_DATABASE}
    depends_on:
      - db
    networks:
      - sql_injection_net

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: sql_injection_phpmyadmin
    restart: on-failure
    environment:
      PMA_HOST: db
      PMA_USER: ${MYSQL_USER}
      PMA_PASSWORD: ${MYSQL_PASSWORD}
      UPLOAD_LIMIT: 64M
    depends_on:
      - db
    networks:
      - sql_injection_net

  nginx:
    build: ./nginx
    container_name: sql_injection_nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - nginx_certs:/etc/nginx/certs
    depends_on:
      - php
      - phpmyadmin
    networks:
      - sql_injection_net

volumes:
  db_data:
  nginx_certs:

networks:
  sql_injection_net:
    driver: bridge
